# Generated by Django 5.1.5 on 2025-02-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speciality',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
