# Generated by Django 5.1.5 on 2025-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_institute_is_active_institute_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
