# Generated by Django 5.1.5 on 2025-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_discipline_name_alter_speciality_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
