# Generated by Django 5.1.5 on 2025-02-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_discipline_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='course',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='study_plan',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='test',
        ),
        migrations.CreateModel(
            name='StudyPlanDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.SmallIntegerField()),
                ('semester', models.SmallIntegerField()),
                ('exam', models.BooleanField()),
                ('test', models.BooleanField()),
                ('lecture', models.IntegerField()),
                ('practice', models.IntegerField()),
                ('lab', models.IntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.discipline')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.studyplan')),
            ],
        ),
    ]
