# Generated by Django 5.1.5 on 2025-02-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_remove_discipline_course_remove_discipline_exam_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discipline",
            name="by_choice",
        ),
        migrations.AddField(
            model_name="studyplandiscipline",
            name="by_choice",
            field=models.BooleanField(default=False),
        ),
    ]
