# Generated by Django 5.1.5 on 2025-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_remove_discipline_by_choice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discipline",
            name="code",
        ),
        migrations.AddField(
            model_name="studyplandiscipline",
            name="code",
            field=models.CharField(default="code", max_length=100),
            preserve_default=False,
        ),
    ]
